-- MySQL Script generated by MySQL Workbench
-- Fri Oct 14 10:32:20 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema znl3-zliheouch_2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema znl3-zliheouch_2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `znl3-zliheouch_2` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema znl3-zliheouch_1
-- -----------------------------------------------------
USE `znl3-zliheouch_2` ;

-- -----------------------------------------------------
-- Table `znl3-zliheouch_2`.`T_COMPTE_CPT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `znl3-zliheouch_2`.`T_COMPTE_CPT` (
  `cpt_id` INT NOT NULL AUTO_INCREMENT,
  `cpt_pseudo` VARCHAR(20) NOT NULL,
  `cpt_mdp` CHAR(64) NOT NULL,
  `cpt_role` CHAR(1) NOT NULL,
  `cpt_etat` CHAR(1) NOT NULL,
  PRIMARY KEY (`cpt_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `znl3-zliheouch_2`.`T_PROFIL_PFL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `znl3-zliheouch_2`.`T_PROFIL_PFL` (
  `cpt_id` INT NOT NULL AUTO_INCREMENT,
  `pfl_nom` VARCHAR(60) NOT NULL,
  `pfl_prenom` VARCHAR(60) NOT NULL,
  `pfl_mail` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`cpt_id`),
  CONSTRAINT `fk_T_PROFIL_PFL_T_COMPTE_CPT1`
    FOREIGN KEY (`cpt_id`)
    REFERENCES `znl3-zliheouch_2`.`T_COMPTE_CPT` (`cpt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `znl3-zliheouch_2`.`T_NEWS_NEW`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `znl3-zliheouch_2`.`T_NEWS_NEW` (
  `new_id` INT NOT NULL AUTO_INCREMENT,
  `new_intitule` VARCHAR(200) NOT NULL,
  `new_description` VARCHAR(500) NULL,
  `new_date` DATETIME NOT NULL,
  `cpt_id` INT NOT NULL,
  PRIMARY KEY (`new_id`),
  INDEX `fk_T_NEWS_NEW_T_COMPTE_CPT1_idx` (`cpt_id` ASC),
  CONSTRAINT `fk_T_NEWS_NEW_T_COMPTE_CPT1`
    FOREIGN KEY (`cpt_id`)
    REFERENCES `znl3-zliheouch_2`.`T_COMPTE_CPT` (`cpt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `znl3-zliheouch_2`.`T_QUIZ_QUI`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `znl3-zliheouch_2`.`T_QUIZ_QUI` (
  `qui_id` INT NOT NULL AUTO_INCREMENT,
  `qui_intitule` VARCHAR(200) NOT NULL,
  `qui_image` VARCHAR(200) NOT NULL,
  `qui_etat` CHAR(1) NOT NULL,
  `cpt_id` INT NOT NULL,
  PRIMARY KEY (`qui_id`),
  INDEX `fk_T_QUIZ_QUI_T_COMPTE_CPT1_idx` (`cpt_id` ASC),
  CONSTRAINT `fk_T_QUIZ_QUI_T_COMPTE_CPT1`
    FOREIGN KEY (`cpt_id`)
    REFERENCES `znl3-zliheouch_2`.`T_COMPTE_CPT` (`cpt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `znl3-zliheouch_2`.`T_MATCH_MAT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `znl3-zliheouch_2`.`T_MATCH_MAT` (
  `mat_id` INT NOT NULL AUTO_INCREMENT,
  `mat_code` CHAR(8) NOT NULL,
  `mat_intitule` VARCHAR(200) NOT NULL,
  `mat_etat` CHAR(1) NOT NULL,
  `cpt_id` INT NOT NULL,
  `qui_id` INT NOT NULL,
  `mat_debut` DATETIME NOT NULL,
  `mat_fin` DATETIME NOT NULL,
  PRIMARY KEY (`mat_id`),
  INDEX `fk_T_MATCH_MAT_T_COMPTE_CPT1_idx` (`cpt_id` ASC),
  INDEX `fk_T_MATCH_MAT_T_QUIZ_QUI1_idx` (`qui_id` ASC),
  UNIQUE INDEX `mat_code_UNIQUE` (`mat_code` ASC),
  CONSTRAINT `fk_T_MATCH_MAT_T_COMPTE_CPT1`
    FOREIGN KEY (`cpt_id`)
    REFERENCES `znl3-zliheouch_2`.`T_COMPTE_CPT` (`cpt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_MATCH_MAT_T_QUIZ_QUI1`
    FOREIGN KEY (`qui_id`)
    REFERENCES `znl3-zliheouch_2`.`T_QUIZ_QUI` (`qui_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `znl3-zliheouch_2`.`T_JOUEUR_JOU`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `znl3-zliheouch_2`.`T_JOUEUR_JOU` (
  `jou_id` INT NOT NULL AUTO_INCREMENT,
  `jou_pseudo` VARCHAR(45) NOT NULL,
  `mat_id` INT NOT NULL,
  `score` DOUBLE NOT NULL,
  PRIMARY KEY (`jou_id`),
  INDEX `fk_T_JOUEUR_JOU_T_MATCH_MAT1_idx` (`mat_id` ASC),
  CONSTRAINT `fk_T_JOUEUR_JOU_T_MATCH_MAT1`
    FOREIGN KEY (`mat_id`)
    REFERENCES `znl3-zliheouch_2`.`T_MATCH_MAT` (`mat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `znl3-zliheouch_2`.`T_QUESTION_QUE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `znl3-zliheouch_2`.`T_QUESTION_QUE` (
  `que_id` INT NOT NULL AUTO_INCREMENT,
  `que_intitule` VARCHAR(200) NOT NULL,
  `que_ordre` INT NOT NULL,
  `que_etat` CHAR(1) NOT NULL,
  `qui_id` INT NOT NULL,
  PRIMARY KEY (`que_id`),
  INDEX `fk_T_QUESTION_QUS_T_QUIZ_QUI1_idx` (`qui_id` ASC),
  CONSTRAINT `fk_T_QUESTION_QUS_T_QUIZ_QUI1`
    FOREIGN KEY (`qui_id`)
    REFERENCES `znl3-zliheouch_2`.`T_QUIZ_QUI` (`qui_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `znl3-zliheouch_2`.`T_REPONSE_REP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `znl3-zliheouch_2`.`T_REPONSE_REP` (
  `rep_id` INT NOT NULL AUTO_INCREMENT,
  `rep_texte` VARCHAR(200) NOT NULL,
  `rep_validité` TINYINT NOT NULL,
  `que_id` INT NOT NULL,
  PRIMARY KEY (`rep_id`),
  INDEX `fk_T_REPONSE_REP_T_QUESTION_QUS1_idx` (`que_id` ASC),
  CONSTRAINT `fk_T_REPONSE_REP_T_QUESTION_QUS1`
    FOREIGN KEY (`que_id`)
    REFERENCES `znl3-zliheouch_2`.`T_QUESTION_QUE` (`que_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
